### PR TITLE
Added regex parsing to remove junk from decoded audio

### PR DESCRIPTION
**Pull request by llotneb**
This pull request will add a simple regex parser to the command center. I've tested it by asking poorly formatted text questions from ccclient.

### CODE REVIEW

**Comment by jhauswald** [comment]
I don't like that the regexes are hardcoded into the command center. Is the objective to have this as a little patch for now or did you want to roll this into the future command center? If so I think it should become its own service that's a query preprocessing service.

This is a good initial implementation that hits what we needed to fix the demo though. What do you think?

**Comment by llotneb** [comment]
You're right -- I guess that the new command center will probably need a query preprocessing service, so  this code should be separate. As you say, I was aiming to make a quick fix for the demo and hadn't considered this.

**Comment by jhauswald** [comment]
@llotneb should we close this for now and you make a new PR then? I don't think this should be merged in its current form given its a quick hack that'll probably change.

**Comment by llotneb** [comment]
Yes, that sounds good. I'm closing it.

**Pull request closed without merging**
