### PR TITLE
Img merge

### PR DESCRIPTION
**Pull request by Lilisys**
The existing files can run as a standalone (with or without DjiNN, no CC) as well as with the command center (also with or without DjiNN). Here's what still needs to be done
- [x] Write a readme (Will be based off the readme in [tonic-common](https://github.com/Lilisys/clarityeco/tree/mergeTonic/tonic-common))
- [x] Incorporate Tim's structural changes for standalone version
- [x] Incorporate Tim's structural changes for cc version
- [x] rebase this (possibly create clean branch and PR from there)

### CODE REVIEW

**Comment by Lilisys** [comment]
@jhauswald Should I remove the code that runs without Djinn? Right now the Djinn flag can be set so the client can run img with or without Djinn. I kept it as a sanity check, but we removed the non-cc version (also a sanity check) so I'm wondering if we just want to get rid of all these checks?

**Comment by jhauswald** [comment]
@Lilisys: I remember we talked about this but I don't remember the conclusion? Can you go through the pros/cons of keeping local execution? I'll wait on taking a look at this until we sort that out.

**Comment by Lilisys** [comment]
Pros:
- testing - let's say you clone the repo and try to run everything at once. Something breaks, but you're not sure where. You can start to find the issue by running it locally, to see if it's related to just the service rather than with DjiNN. 
- In the same vein, maybe you're adding enhancements or something. You can test them by running locally vs with DjiNN to see if you're getting the same output. 

Cons:
- more code to read through/maintain, like if caffe changes its structure
- (not sure if this a pro or a con but) Image will have to interact with caffe, rather than just having Djinn interact.

**Comment by jhauswald** [comment]
One problem I see of this is: say another service comes in that in a similar way needs another one to execute. We wouldn't add code to do it locally, we would just call the other service. We should have a standard scheme for this. I also anticipate if you have the local execution but the service changes, then you have to maintain more code and a bug could replicate itself across multiple (copied) code.

If that local execution wasn't in there it wouldn't be a thought. We should get rid of it and **clearly** document in the documentation AND wiki what services it depends on. Also for #41.

Agree?

**Comment by Lilisys** [comment]
Sounds good. I'll change the service and documentation (which is the wiki?? or do you mean readme and wiki?)

**Comment by Lilisys** [comment]
@jhauswald I've applied the changes to the caffe macro in this [PR](https://github.com/jhauswald/caffe/pull/1)

**Comment by jhauswald** [comment]
The command center:
```
starting command center @localhost:8000
receiving register message from service djinn running @localhost:8080
receiving register message from service imp running @localhost:8081
receiving query statistic update from service imp@localhost:8081 for 91321 ms
```
From the DjinnService:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0804 19:34:07.578711 26334 DjinnService.cpp:296] Starting the Djinn service...
I0804 19:34:07.581415 26334 DjinnService.cpp:140] registering to command center running at localhost:8000
I0804 19:34:07.600309 26334 DjinnService.cpp:142] service djinn successfully registered
I0804 19:34:07.600343 26334 DjinnService.cpp:301] service Djinn is ready...
I0804 19:35:58.288399 26353 DjinnService.cpp:79] receiving djinn data at Tue Aug  4 19:35:58 2015
I0804 19:35:58.288444 26353 DjinnService.cpp:166] The reqname is imc
I0804 19:35:58.288455 26353 DjinnService.cpp:168] The data size is 463761
E0804 19:35:58.289017 26353 DjinnService.cpp:174] Task imc not found.
Segmentation fault (core dumped)
```

From IMGService:
```
I0804 19:34:27.069087 26372 IMGService.cpp:220] Command Center returns localhost:8080
I0804 19:34:27.069255 26372 IMGService.cpp:226] Setting tags
I0804 19:34:27.069342 26372 IMGService.cpp:239] Request Name: imc
I0804 19:34:27.069353 26372 IMGService.cpp:240] Length: 463761
I0804 19:34:27.069361 26372 IMGService.cpp:241] Setting input data...
E0804 19:35:58.382205 26372 IMGService.cpp:262] Could not talk to Djinn
I0804 19:35:58.382244 26372 IMGService.cpp:353] Image: common-img/input/imc/dog-208-227.jpg class: 
I0804 19:35:58.382252 26372 IMGService.cpp:353] Image: common-img/input/imc/cat-281-227.jpg class: 
I0804 19:35:58.382258 26372 IMGService.cpp:353] Image: common-img/input/imc/tp-999-227.jpg class: 
I0804 19:35:58.387953 26372 IMGService.cpp:92] update the command center latency statistics (91321ms)
Thrift: Tue Aug  4 19:35:58 2015 TSocket::read() recv() <Host: ::ffff:127.0.0.1 Port: 59240>Connection reset by peer
```

**Comment by Lilisys** [comment]
I can't seem to replicate this error. That error occurs at line [174](https://github.com/clarityinc/clarityeco/blob/dev/djinn/DjinnService.cpp#L174) of DjinnService.cpp, and it occurs when the task isn't in the nets. DjiNN gets the nets when it calls train(), and the nets are in nets.txt. Is nets.txt in the same directory as DjinnServer.cpp for you? Also, what arguments are you giving the client?

**Comment by jhauswald** [comment]
Ok yes I was missing `nets.txt`. Its tricky having to bounce around branches making sure I have the correct stuff to run everything, we need to figure out a better way to do that.

Now it works I get the correct result but its unbearably slow. Its that just me or do you have the same issue? The forward pass takes ~300ms from the output and the task client takes 83s, where is the rest of the time being spent??

**Pull request merged**
